### ISSUE TITLE
8k version

### ISSUE THREAD

**Issue by mattvenn** [mwelling/beagle-wire#13]
Great project - I'm interested if you ever make a run of boards... but I would prefer an 8k version!

**Comment by stefanct** [comment]
i am not associated with the project... but one problem with the 8k is that its available in BGA packages only...

**Comment by mwelling** [comment]
An 8K version is in the works. If the crowd supply hits 150% we will deliver 8K units. Otherwise we might open a new campaign for the 8K. And yes we opted out of doing an 8K design at first because of time constraints for the GSoC project and I had to hand assemble the units.

I can hand assemble the BGA versions but I rather not.
